### ISSUE TITLE
Vertical scrollbar (in sample demo)

### ISSUE THREAD

**Issue by Deleplace** [dgageot/demoit#19]
(Observed on Linux)

The right scrollbar is always visible, regardless the actual height of my browser window. It's still visible in Fullscreen.

![demoit_scrollbar](https://user-images.githubusercontent.com/13508141/54528353-0ed39e00-497d-11e9-91c9-3cb8cafec543.png)

**Comment by gfeun** [comment]
Same for me on Debian, with Firefox and Chromium.
Fixed this by changing this line: https://github.com/dgageot/demoit/blob/51779bd37f3cfc1a67b828531f66f9af702d8c9d/sample/.demoit/style.css#L69
to 
```css
height: 90vh;
```
I think this is due to the top class being 100% vertical height **+ 1.5em** of padding-top leading to > 100% height space and the appearance of the scrollbar.

**Comment by dgageot** [comment]
This is fixed now
